#Nome da lenda
spring.application.name=UniespTechhh


#Banco de dados H2 roda na nemorius prático pra test du ba ridu
spring.datasource.url=jdbc:h2:mem:uniesp_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Pra gente conseguir ver a tabelinha no navegador depois localhost:8080/h2-console
spring.h2.console.enabled=true

# Mostra no console o que o Spring tá fazendo por baixo dos panos as queridas do SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update